name: Bump Tag
on:
  push:
    branches:
      - master
      - develop
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with:
        fetch-depth: '0'
    - name: bump_version
      uses: anothrNick/github-tag-action@1.17.2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        WITH_V: true
        DRY_RUN: true
    - id: step1
      run:  echo  ${{needs.bump_version.outputs.new_tag}}
    - run:  echo ${{needs.bump_version.outputs.tag }}
    - run: echo  ${{ github.head_ref }}
    - run: echo  ${{ github.event_name }}
    - run: echo  ${{ github.event.action }}
