name: Bump Tag
on:
  push:
    branches:
      - master
      - develop
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with:
        fetch-depth: '0'
    - name: bump_version
      uses: anothrNick/github-tag-action@1.17.2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        WITH_V: true
    - id: step1
      run:  echo ${{needs.bump_version.outputs.new_tag}} ${{needs.bump_version.output.tag}} ${{ github.ref }} ${{ github.event.action }}
