name: Bump Tag
on:
  push:
    branches:
      - master
      - develop
jobs:
  bump_tag:
    runs-on: ubuntu-latest
    name: Bump tag
    steps:
    - uses: actions/checkout@master
      with:
        fetch-depth: '0'
    - name: 'Get Previous tag'
      id: previoustag
      uses: "WyriHaximus/github-action-get-previous-tag@master"
      env:
        GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
    - name: 'Get next minor version'
      id: semvers
      uses: "WyriHaximus/github-action-next-semvers@master"
      with:
        version: ${{ steps.previoustag.outputs.tag }}
    - name: git tag
      run: echo ${{ steps.previoustag.outputs.tag }} ${{ steps.previoustag.semvers.tag }}
    - name: set env
      run: echo "::set-env name=tag::${{ steps.previoustag.semvers.tag }}"
#     - name: bump_version
#       uses: anothrNick/github-tag-action@1.17.2
#       env:
#         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#         WITH_V: true
#         DRY_RUN: true
#     - id: step1
#       run:  echo  ${{needs.bump_version.outputs.new_tag}}
#     - run:  echo ${{needs.bump_version.outputs.tag }}
#     - run: echo  ${{ github.ref.heads }}
#     - run: echo  ${{ github.event_name }}
#     - run: echo  ${{ git describe }}
      
  build_master:
    name: Create Release
    needs: [bump_tag]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - run: echo $tag
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          draft: false
          prerelease: false
